apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: hello
    image: "p31arm64v8/centos:7.6.1810"
    command: ["/bin/echo", "hello", "world"]
