kind: PersistentVolume
apiVersion: v1
metadata:
  name: syndesis-pv
  labels:
    type: local
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/registry"


