apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: prometheus
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-prometheus
spec:
  tags:
  - from:
      kind: DockerImage
      name: docker.io/p31arm64v8/prometheus:v2.2.0
    importPolicy:
      scheduled: true
    name: "v2.2.0"
