apiVersion: v1
kind: ServiceAccount
metadata:
  name: syndesis-prometheus
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-prometheus
