apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syndesis-prometheus
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: infrastructure
    syndesis.io/component: syndesis-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
